website_homepage:
    path:     /
    defaults: { _controller: websiteBundle:Homepage:index }
reset_password:
    path:     /user/password/reset/
    defaults: { _controller: websiteBundle:Homepage:resetPassword }

agenda:
    path:     /agenda/
    defaults: { _controller: websiteBundle:Agenda:index }

feed:
    path:     /feed/
    defaults: { _controller: websiteBundle:Feed:index }

conversation:
    path:     /conversation/
    defaults: { _controller: websiteBundle:Conversation:index }

privacy_policy:
    path:     /privacy_policy/
    defaults: { _controller: websiteBundle:Legal:privacyPolicy }

quick_registration:
    path:     /quick_registration/
    defaults: { _controller: websiteBundle:QuickRegistration:index }
complete_registration:
    path:     /complete_registration/
    defaults: { _controller: websiteBundle:QuickRegistration:completed }

create_association:
    path:     /create_association/
    defaults: { _controller: websiteBundle:CreateAssociation:index }

jeu-concours:
    path:     /jeu-concours/
    defaults: { _controller: websiteBundle:EventGame:index }

search:
    path:     /search/
    defaults: { _controller: websiteBundle:Search:index }

profil_student:
    path:     /profila/
    defaults: { _controller: websiteBundle:Profil:student }

profil_association:
    path:     /profilb/
    defaults: { _controller: websiteBundle:Profil:association }

update_profil:
    path:     /update_profil/
    defaults: { _controller: websiteBundle:Profil:update }