# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        coreBundle\Entity\WebsiteStyxuserbase: sha256

#    role_hierarchy:
#            ROLE_ADMIN:       ROLE_USER

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        main:
          id: fos_user.user_provider.username_email

#        fos_userbundle:
#                    id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
             pattern:        ^/
             anonymous:      true
             provider:       main
             form_login:
                 login_path: fos_user_security_login
                 check_path: fos_user_security_check
                 default_target_path: /feed
                 csrf_token_generator: security.csrf.token_manager
             logout:
                 path:       fos_user_security_logout
                 target:     /
             remember_me:
                 key:        %secret% # %secret% est un paramètre de parameters.yml
#        main:
#            pattern: ^/
#            form_login:
#                provider: fos_userbundle
#                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
#            logout:       true
#            anonymous:    true

    access_control:
            - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/api/, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/create_association, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/create_association, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, role: ROLE_USER }
#            - { path: ^/admin/, role: ROLE_ADMIN }
#        main:
#            anonymous: ~
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
