website_post:
    type: rest

webservice_homepage:
    path:     /api
    defaults: { _controller: WebserviceBundle:Post:PostZoneList }

post:
    type:     rest
    resource: WebserviceBundle\Controller\PostController