<?php

namespace coreBundle\Repository;

/**
 * ApiAuthRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApiAuthRepository extends \Doctrine\ORM\EntityRepository
{
}
