<?php

namespace coreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
* CombatsRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class PostPostZonesRepository extends EntityRepository
{
  public function findById(Integer $id) {
    $repository = $this->getEntityManager()->getRepository('coreBundle:PostPostZones');

    $query = $repository->createQueryBuilder('c')
      ->where('c.id = $id')

    $result = $query->getQuery()->getResult();
    return $result;
  }

  public function findByZone(Integer $zoneId) {
    $repository = $this->getEntityManager()->getRepository('coreBundle:PostPostZones');

    $query = $repository->createQueryBuilder('c')
      ->where('c.zone = $zoneId')

    $result = $query->getQuery()->getResult();
    return $result;
  }
}
