<?php

namespace coreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
* CombatsRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class WebsiteZoneRepository extends EntityRepository
{
  public function findFightWithOneUser()
  {
    $repository = $this->getEntityManager()->getRepository('coreBundle:WebsiteZone');

    $query = $repository->createQueryBuilder('c')
      ->where('c.user2 IS null')
      ->orderBy('c.waitingTime', 'DESC');

    $result = $query->setMaxResults(1)->getQuery()->getResult();
    return $result;
  }
}
