<?php

namespace coreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
* CombatsRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class WebsiteStyxuserbaseRepository extends EntityRepository
{
  public function findById(Integer $id)
  {
    $repository = $this->getEntityManager()->getRepository('coreBundle:WebsiteStyxuserbase');

    $query = $repository->createQueryBuilder('c')
      ->where('c.id = $id')

    $result = $query->getQuery()->getResult();
    return $result;
  }
}
