<?php

namespace coreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WebsiteDepartmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteDepartmentRepository extends EntityRepository
{
}
